In [ ]:
import torch

# Tensor creation
a = torch.tensor([1, 2, 3])
b = torch.zeros((2, 3))
c = torch.ones((3, 3))
d = torch.rand((2, 2))
e = torch.arange(0, 10, 2)

print(a)
print(b)
print(c)
print(d)
print(e)

# Data types
f = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f.dtype)


tensor([1, 2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3712, 0.4482],
        [0.4628, 0.2206]])
tensor([0, 2, 4, 6, 8])
torch.float32


In [ ]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Arithmetic
print(x + y)
print(x * y)

# Broadcasting
z = torch.tensor([10, 20])
print(x + z)

# Indexing
print(x[0])
print(x[:, 1])

# Reshaping
print(x.view(4))
print(x.reshape(1, 4))


tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[11, 22],
        [13, 24]])
tensor([1, 2])
tensor([2, 4])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])


In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 2 * x

y.backward()
print("Gradient:", x.grad)


Gradient: tensor(14.)


In [ ]:
# question 2

In [ ]:
import tensorflow as tf

A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Matrix Addition
print(tf.add(A, B))

# Matrix Multiplication
print(tf.matmul(A, B))

# Transpose
print(tf.transpose(A))

# Determinant
print(tf.linalg.det(A))

# Inverse
print(tf.linalg.inv(A))


tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(-2.0, shape=(), dtype=float32)
tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


In [ ]:
# question 3

In [ ]:
import numpy as np

def perceptron(x, w, b):
    return 1 if np.dot(x, w) + b >= 0 else 0

# AND Gate
w_and = np.array([1, 1])
b_and = -1.5

# OR Gate
w_or = np.array([1, 1])
b_or = -0.5

inputs = [(0,0), (0,1), (1,0), (1,1)]

print("AND Gate")
for x in inputs:
    print(x, perceptron(x, w_and, b_and))

print("\nOR Gate")
for x in inputs:
    print(x, perceptron(x, w_or, b_or))


AND Gate
(0, 0) 0
(0, 1) 0
(1, 0) 0
(1, 1) 1

OR Gate
(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 1


In [ ]:
# question 3

In [ ]:
import numpy as np

def perceptron(x, w, b):
    return 1 if np.dot(x, w) + b >= 0 else 0

# AND Gate
w_and = np.array([1, 1])
b_and = -1.5

# OR Gate
w_or = np.array([1, 1])
b_or = -0.5

inputs = [(0,0), (0,1), (1,0), (1,1)]

print("AND Gate")
for x in inputs:
    print(x, perceptron(x, w_and, b_and))

print("\nOR Gate")
for x in inputs:
    print(x, perceptron(x, w_or, b_or))


AND Gate
(0, 0) 0
(0, 1) 0
(1, 0) 0
(1, 1) 1

OR Gate
(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 1


In [ ]:
# question 4

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# XOR Dataset
X = torch.tensor([[0,0],[0,1],[1,0],[1,1]], dtype=torch.float32)
y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32)

# Neural Network
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

# Training
for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()

print("Predictions:")
print(model(X).round())


Predictions:
tensor([[0.],
        [1.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


In [ ]:
# question 5

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Data
X = torch.unsqueeze(torch.linspace(0, 10, 100), dim=1)
y = 3 * X + 2 + torch.randn(X.size())

# Model
model = nn.Sequential(
    nn.Linear(1, 10),
    nn.ReLU(),
    nn.Linear(10, 1)
)

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training
for epoch in range(1000):
    optimizer.zero_grad()
    pred = model(X)
    loss = criterion(pred, y)
    loss.backward()
    optimizer.step()

print("Final Loss:", loss.item())


Final Loss: 4.845308780670166
